language: java
jdk:
  - openjdk11
services:
  - docker
  - mongodb
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

before_script:
  - sleep 15

script:
  - ./gradlew build
  - docker build -f Dockerfile -t yosri96/task-tracker .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: main