language: java
jdk:
  - openjdk11
service:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - ./gradlew build
  - docker build -f Dockerfile -t task-tracker .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: main